redis:
# Setting this to true enables server name synchronization using Redis
  enable: $KUVEL_REDIS_ENABLED
# Name synchronization is performed only between servers with the same Redis server and the same group-name
  group-name: "$KUVEL_REDIS_GROUP"
  connection:
    hostname: "$KUVEL_REDIS_HOST"
    port: $KUVEL_REDIS_PORT
    username: "$KUVEL_REDIS_USER"
    password: "$KUVEL_REDIS_PASS"
