# Config version. Do not change this
config-version = "1.0"

bind = "0.0.0.0:25565"
motd = "$MOTD"
show-max-players = 8
online-mode = true
player-info-forwarding-mode = "modern"
forwarding-secret = "b4S3DS3Cr3T5"
announce-forge = false

[servers]
# DOESN'T WORK WITH NORMAL VELOCITY
# REQUIRES MY PATCH
# ELSE ERROR CAUSE CONF INVALID
try = ["lobby"]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = 6
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
proxy-protocol = false

[query]
enabled = false
port = 25577
map = "Velocity"
show-plugins = false

[metrics]
enabled = false
